### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by m3a1d2** [Tehzombie-secret/Marketplace-previewer#2]
Hi. How about adding functionality?
You can take similar rules from the site itself.
Need to sort by popularity. This will greatly simplify the search for products with a lot of reviews.

**Comment by Tehzombie-secret** [comment]
![image](https://user-images.githubusercontent.com/108356592/195994731-d0752f9c-bbe0-4f65-ad2b-3981bea74c9e.png)
It is already sorted by popularity, which is a default sort. Be advised that
- popularity in terms of violet marketplace is not a feedback ratio, but more like a set of its own heuristics. Probably it doesn't even include feedbacks quantity as a sort signal. Or does, who knows?
- every search request is personalized (by search history, geolocation, ad reactions and many more factors). In current implementation it's more like a snapshot of a search which was actually made some time ago, but even so sort is always mutating depending on marketplace algorithms maintained by a huge marketing team, so be prepared that it doesn't match the order when you're traversing the violet marketplace.
- there's also a sort by rating. I tried it, but it also doesn't correlate with feedback quantity.

I'm gonna close the issue since there's not so much to add. As for me - I don't use search much since there's a better discover route:
- visit an item
- look into person's feedback list
- find items of interest
- repeat until infinity
But I do believe that every person uses the tool differently. Sorry that I can't help much on this one.
